module Mrnorm

	!----------------------------------------------------------------
	! Subroutine for making random variable from normal distribution,
	! from random variable from uniform distribution.
	!----------------------------------------------------------------
	private

	public :: rnorm


	contains

		subroutine rnorm ( av, st, rn )

			use mt
			implicit none

			real*8, intent(in)  :: av, st
			real*8, intent(out) :: rn

			integer  :: i, seed
			real*8   :: r1, r2, w1, w2
			real*8, parameter :: pi = 3.14159265d0

			r1 = grnd()   !::: uniform random numbers
						  !::: generated by the Mersenne Twister 'mt.f'
			r2 = grnd()

			!::: Box-Muller method for generating normal random numbers
			!     nRand1=σ*sqrt(-2*log(Rand1))*cos(2*PI*Rand2)+m
			!     nRand2=σ*sqrt(-2*log(Rand1))*sin(2*PI*Rand2)+m

			w1 = sqrt( -2.0d0 * log( r1 ) )
			w2 = sin( 2.0d0 * pi * r2 )
		!   w2 = cos( 2.0d0 * pi * r2 )
			rn = av + st * w1 * w2


		end subroutine rnorm
end module Mrnorm
